# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-17 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0003_auto_20181017_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minionlist',
            name='cpu_model',
        ),
        migrations.RemoveField(
            model_name='minionlist',
            name='cpu_num',
        ),
        migrations.AddField(
            model_name='minionlist',
            name='cpu_info',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU信息'),
        ),
    ]
