# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-17 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0004_auto_20181017_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minionlist',
            name='cpu_info',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU信息'),
        ),
    ]
