# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-16 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='菜单名称')),
                ('path', models.CharField(max_length=100, verbose_name='菜单地址')),
                ('icon', models.CharField(max_length=128, verbose_name='菜单图标')),
                ('parent_menus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_menu', to='menus.Menu')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
            },
        ),
    ]
